### ISSUE TITLE
Nyere brukere får ikke lagt til data-sources

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-admin-gui#100]
Hvis en ny bruker forsøker å legge til en datakilde, får brukeren en blank side:
![image](https://user-images.githubusercontent.com/8625716/130436414-babbf144-825a-425b-8b8f-8ea5892fd0e8.png)
![image](https://user-images.githubusercontent.com/8625716/130436490-f49ab467-cc0f-4108-98bc-f878461cfb9c.png)

Mistanken ligger på publisherId, og at denne består av en tom liste

**Comment by KurtStian** [comment]
Her er henvedelsen fra brukeren:
[Sv_ Oppdatering på mottatt henvendelse - [Altinn SD4903649]_ Registrere høster.pdf](https://github.com/Informasjonsforvaltning/fdk-admin-gui/files/7032158/Sv_.Oppdatering.pa.mottatt.henvendelse.-.Altinn.SD4903649._.Registrere.hoster.pdf)
![image](https://user-images.githubusercontent.com/43232700/130453093-f6cbf9e1-1ce4-42df-bd1d-eed820731efd.png)
![image](https://user-images.githubusercontent.com/43232700/130453211-6cd59bc6-6aba-4ae0-8ed7-013d67d63a68.png)

**Comment by shenluna** [comment]
Testet OK i demo
