### ISSUE TITLE
Implementere en "Test URL" knapp

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-admin-gui#24]
Vi bør lage ein knapp (som feks er rett over Harvest-knappen) som bruker kan trykke på for å teste at endepunktet.

Applikasjonen sender en request tilsvarande
```
curl -X GET -H "Accept: {Data type}" [URI}
```
Bruker skal få success-melding dersom respons er 200 OK, failure-melding ellers.

**Comment by lillelars** [comment]
@stigbd Dette har vi løst på en annen måte. Regner med det er tilstrekkelig med "Valider"-knappen i fdk-admin som tar bruker til validatoren vår....

Kan vi lukke denne saken?

**Comment by stigbd** [comment]
Enig. Å validere vil innebære ein slik test som issue adresser. Kan lukkast.
