### ISSUE TITLE
Bugs mot Admin-gui NY Rolle

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-admin-gui#57]
- [ ] Bruker MÅ refreshe før han får lov til å slette eller endre det endepunktet han har lagt inn? Steg for å gjenskape:
- Legg inn nytt høsteendepunkt i admin
- Forsøk å slett det
- forsøk å endre på det
- refresh siden
- nå får bruker lov å slette endepunktet?
![image](https://user-images.githubusercontent.com/39513382/90601685-dfbbfe80-e1f8-11ea-9353-c9353826ce45.png)

- [x] Sett default view til "Data sources"

- [x] Super admin mangler masse endepunkter (??)

- [x] Valideringsregler trigger feilaktig når jeg forsøker å legge inn nye endepunkter

**Comment by lillelars** [comment]
@azaxarov fant en liten bug til som må håndteres - se beskrivelse over.

**Comment by joebrreg** [comment]
Testet ok!
