### ISSUE TITLE
[data-sources] Filter på publisher

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-admin-gui#61]
Som administrator (superbruker) 
Når eg går til https://admin.fellesdatakatalog.digdir.no/data-sources, får eg høve til å filtrere trefflista på publisher
Slik at eg kun ser data-sources tilknytta den gitte publisher.

**Comment by KjerstiSteien** [comment]
@KurtStian fortsatt behov for dette?

**Comment by KurtStian** [comment]
@KjerstiSteien Løsningen har i dag muligheten til å søke på utgiver. Hvis man legger inn org.nummer/navnet til virksomheten i søket så får man opp alle datakildene til denne utgiveren. Tenker at dette er godt nok.
