### ISSUE TITLE
Navn på endepunktet bør være navn på virksomheten

### ISSUE THREAD

**Issue by sindresandvik2** [Informasjonsforvaltning/fdk-admin-gui#66]
Når systemet automatisk opprette et nytt høsteendpunkt når en "ny" virksomhet publiserer sitt aller første begrep så er det vanskelig å lese ut hvilken virksomhet det gjelder siden organisasjonsnummer blir brukt.  Orgnummer i Description bør erstattes med Virksomhetsnavn

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/0408d489-67af-4853-af4c-0d07383243ab)

Se også issue # 2604

**Comment by lillelars** [comment]
Denne er utdatert. Vi har nytt design - lukker saken.
