### ISSUE TITLE
Opprette høsteendepunkt + trigge harvesting automatisk

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-admin-gui#67]
Ved førstegangsregistrering bør dette bli opprettet i fdk-admin-gui for tilhørende organisasjon.
Dette bør skje for alle registreringskanalene vi har i løsningen vår; 

- [x]  datasett
- [x] apier
- [x] begreper

**Comment by jeffreiffers** [comment]
Lagt til datatype og automatiske tester som verifiserer at meldingen blir sendt på køen.

**Comment by shenluna** [comment]
Testet i demo
