### ISSUE TITLE
Legge til validering mot DCAT-validatoren vår

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-admin-gui#73]
Se design:
https://eggedosis.github.io/fdk-design/redirects/register/admin/start-default-desktop.html

- [ ] Støtte for å legge til URL som parameter

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/105869302-602c2a00-5ff7-11eb-8637-43718d6e274d.png)
