### ISSUE TITLE
Hente og vise organisasjonsnavn for endepunkt

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-admin-gui#74]
For hvert endepunkt er det ønskelig å vise både organisasjonsnummer og navn.

Se design:
https://eggedosis.github.io/fdk-design/redirects/register/admin/start-default-desktop.html

**Comment by shenluna** [comment]
Testet i staging

![image](https://user-images.githubusercontent.com/73637969/107779413-98e13880-6d45-11eb-9767-a754850babb7.png)

**Comment by shenluna** [comment]
Når man er superbruker og har tilgang til flere kataloger vises ikke navnene på alle
![image](https://user-images.githubusercontent.com/73637969/107784241-7ce09580-6d4b-11eb-9f90-b83afdea6059.png)

**Comment by shenluna** [comment]
Testet i staging
