### ISSUE TITLE
Legge til støtte for å høste hendelser

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-admin-gui#81]

**Comment by stigbd** [comment]
Ligger ikkje dette innebygd i høsting av public-services? Slik eg har forstått det, vil hendelsene kome med når vi høster tjenester.

**Comment by lillelars** [comment]
@stigbd  per nå gjør det det, målet er å skru dette av og ha en egen for hendelser

**Comment by lillelars** [comment]
@stigbd  Slik at vi kalrer å høste hendelser som står fritt

**Comment by stigbd** [comment]
Ok. Fins det eit behov for dette? Fins det endepunkter med _kun_ hendelser? Fint med referanse til behovs-issue viss dette fins. Viss ikkje, bør det vel adresserer der først.

**Comment by jeffreiffers** [comment]
Hva skjer med denne saken?

**Comment by lillelars** [comment]
Denne er løst. Lukker saken.
