### ISSUE TITLE
Endringer i fdk-admin-gui

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-admin-gui#85]
**Features:**

- [x] Legge til en ekstra utgang av modal-vinduet
![image](https://user-images.githubusercontent.com/39513382/108977951-627eb400-7689-11eb-8424-f7e93d271e95.png)

- [x] aksessering av felter via tastatur (UU-krav)

- [x] Bør ikke / trenger ikke validere inputfeltene her før bruker trykker "Lagre"
![image](https://user-images.githubusercontent.com/73637969/108980272-c904d180-768b-11eb-8dfd-feae01951bbc.png)
![image](https://user-images.githubusercontent.com/73637969/108980301-cefab280-768b-11eb-8a5a-4ae5340efb4a.png)
![image](https://user-images.githubusercontent.com/73637969/108980324-d326d000-768b-11eb-80ad-d0a30aedf22b.png)

- [x] Legge til organisasjonsnummer i parantes som valg i dropdown.
F.eks: Ramsund og Rognad (910244132)

- [x] Hvis bruker har valgt katalog først, bør det bare være mulig å begrense til og vise bare tilhørende spesifikasjoner for valgt katalog.
F.eks: Datasett valgt => bare mulig å velge DCAT-AP-NO 
Begrep valgt => bare mulig å velge SKOS-AP-NO

- [x] Hvis bruker har valgt spesifikasjon først, bør valideringsmelding endres fra: "Data standard is not supported for XXX" til "Spesifikasjonen er ikke støttet av denne type katalog." inntil bruker faktisk velger korrekt katalog da :) 

- [x] Ledetekst for inputfelt under "Beskrivelse" bør være: "f.eks Datakatalog for Ramsund og Rognad"

- [x] Validering av gyldig URL

**Tekstendringer i modal-skjemaet:**

- [x] Publiserer --> Utgiver
- [x] Url --> URL til datakilde
- [x] Beskrivelse --> Navn på datakilde

**Tekstendringer i admin-gui**
- [x] Content type --> Format: 

**Tekstendringer i valideringer:**

- [ ] Publiserer: "Organization number is required" --> "Organisasjon mangler"
- [x] Katalog: --> "Velg katalog datakilden hører til"
- [x] Datakildetype : "Data standard is not supported for datasets" --> "Velg spesifikasjon for datakilden"
- [ ] Format: "Må velge formatet datakilden er på"

**Comment by jeffreiffers** [comment]
"Organisasjon mangler" har jeg ikke brukt. Isteden er det "Utgiver er obligatorisk"

Denne skjønner jeg ikke: Format: "Må velge formatet datakilden er på"

**Comment by shenluna** [comment]
Enig kommentarene dine. Ser du har lagt til "(felt x) er obligatorisk", jeg vil si det er tilstrekkelig.
To ting som mangler.

1. 'Content type' skal endres til 'Format' i adminoversikten:
![image](https://user-images.githubusercontent.com/73637969/109474792-29718580-7a75-11eb-97ff-488e678c924f.png)

2. Når man navigerer med tastaturet og velger en noe fra en rull-meny så mister den fokus, når man da trykker på tab starter den fra begynnelsen. Bør fortsette der man er.

**Comment by shenluna** [comment]
Testet i staging og verifisert i demo
