### ISSUE TITLE
Legge til komponenter i @fellesdatakatalog (fdk-kit)

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-admin-gui#86]
NB! Etter komponenten er lagt til i fdk-kit skal den også brukes i løsningen vår.

- [ ] side menu
- [x] expansion panel
- [ ] input field
- [ ] checkbox
- [ ] radio
- [ ] select
- [ ] logo
- [ ] table / sortable & filterable list
- [ ] modal
- [ ] page layout
- [ ] colors
- [ ] icons

**Comment by KjerstiSteien** [comment]
@jeffreiffers @Lillebo Er dette fortsatt relevant? Eller går vi bort fra egne komponenter?
